### ISSUE TITLE
Refactoring of the source code

### ISSUE THREAD

**Issue by g4m3r0** [EshanTrivedi21/Git-CheatSheet#100]
The source code of the index.html and styles.css file seems to have some formatting issues (missing or wrong indentation, empty lines) and typos.
I also think putting the Javascript code into a dedicated file would be better.

If you don't mind then I would like to work on this issue two.

**Comment by EshanTrivedi21** [comment]
Go on with it buddy

**Comment by EshanTrivedi21** [comment]
What's the progress @g4m3r0 ?

**Comment by g4m3r0** [comment]
@EshanTrivedi21 I have
- Refactored/Beautified HTML
- Separated JavaScript code into its own file
- Fixed some typos.
Can you please take a look at it?

**Comment by EshanTrivedi21** [comment]
Resolved
