### ISSUE TITLE
Side Navbar UI and Responsiveness

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#104]
`Q1: Is your feature request related to a problem? Please describe.`

Responsiveness of the Website

`Q2: Describe the solution you'd like`

Creating a hamburger navbar for the sidebar

`Q3: Describe alternatives you've considered`

none

`Q4: Additional context`

none

**Comment by EshanTrivedi21** [comment]
Take Charge @vaibhav-009 !

**Comment by Manishgupta200** [comment]
I would like to work on that issue as i solved this issue recently

**Comment by EshanTrivedi21** [comment]
The hamburger navbar is already done by someone.. But I can assign you to enhance the UI and Working of the Navbar
Thanks for your Involvement @Manishgupta200 🚀

**Comment by Manishgupta200** [comment]
Ya. @EshanTrivedi21 but please assign me first. I'm excited to work on the issue

**Comment by Manishgupta200** [comment]
Thanks for assigning

**Comment by Manishgupta200** [comment]
Please look at "pull request" section @EshanTrivedi21
