### ISSUE TITLE
Showing 404 Error

### ISSUE THREAD

**Issue by subhans11** [EshanTrivedi21/Git-CheatSheet#107]
Sidebar working fine for options, but for the last 2 options (Extensions for Github) it showing 404 error.

![Screenshot (169)](https://user-images.githubusercontent.com/102163333/197323528-21b5c819-0697-44f4-9b5a-be7a00abe803.png)

![404](https://user-images.githubusercontent.com/102163333/197323531-75d1e431-4c9a-43a5-b8ad-648912dc6489.PNG)

**Comment by EshanTrivedi21** [comment]
Assigning you this issue!

**Comment by subhans11** [comment]
working fine now, No edit needed. closing the isssue.
