### ISSUE TITLE
Adding a new command

### ISSUE THREAD

**Issue by hemant-sw** [EshanTrivedi21/Git-CheatSheet#108]
Hi @EshanTrivedi21 in git branching section of the website it would be great if we add git command to view all branches.
git branch -a 

This command will so all branches So, If you think that this can be added you can assign me this issue and it will be great if you label it with hacktoberfest.

Thank you.

**Comment by EshanTrivedi21** [comment]
I have assigned you this task @hemant-sw 
Please change this in the Website and the Markdown
Thanks for your involvement 🚀

**Comment by EshanTrivedi21** [comment]
closing this
