### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#112]
### This is the biggest issue being faced by everyone using the code

+ ### Create a separate JS file in the assets folder and remove the Internal JS.
+ ### Delete Unwanted Variables in the CSS file and use a proper name convention.
+ ### Format the Code, Use DRY Principle to do so.
+ ### Remove unwanted lines of code but also check that it doesn't alter the output.

**Comment by Bhavil-13** [comment]
I want to take up this issue, I only know HTML, CSS and JS. @EshanTrivedi21

**Comment by EshanTrivedi21** [comment]
Go on @Bhavil-13, assigning you the task

**Comment by EshanTrivedi21** [comment]
@Bhavil-13 i have made some major UI changes, plz pull the code once before sending a pr or working on it to prevent merge conflicts.
