### ISSUE TITLE
Converting cheatsheet to asciidoc

### ISSUE THREAD

**Issue by Kedap** [EshanTrivedi21/Git-CheatSheet#12]
It would be better to convert the txt file to asciidoc to later convert to markdown

**Comment by EshanTrivedi21** [comment]
Heyy,
I have less idea about this.. Never used asciidoc just read about it.
I'll assign you the task it would be great if you help me out with this.
Thank You,
Regards.

**Comment by jyotika6221** [comment]
Hey please assign me this task.

**Comment by Kedap** [comment]
Douh

**Comment by Kedap** [comment]
I already have the pull request ready
