### ISSUE TITLE
Enhancing the project by adding "Find yourself in Github" section in the page

### ISSUE THREAD

**Issue by pooranjoyb** [EshanTrivedi21/Git-CheatSheet#127]
#### Reason/Context

Why we need this improvement?
It would be great if a user is able to find himself/herself in Github after installing and authenticating

How will this change help?
It will enhance the UI of the webpage. It will ensure users to type their username the input section which will return the username, profile-pic, bio, repos of the user. Hence giving a better user-experience.

#### Description

What changes have to be introduced?
The Github users API will help us to access to a bunch of data about GitHub users like names, followers, images, and many more.

Will this be a breaking change?
No, it will enhance the project.

How could it be implemented/designed?
This can be achieved by fetching user information with the help of API and using JavaScript method,
i.e, by writing few lines of JavaScript and serving them in the webpage.

### Would be glad to work on this if you assign me. @EshanTrivedi21 :)

**Comment by EshanTrivedi21** [comment]
Hey @pooranjoyb, Glad you're here! Already assigned this task to you, hope you have a great time working over it.

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb, Glad you're here! Already assigned this task to you, hope you have a great time working over it. 

Sure, Already into it! ❤

**Comment by EshanTrivedi21** [comment]
Great work @pooranjoyb , marking this issue as completed!
