### ISSUE TITLE
Incomplete Website

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#22]
The text file need to be transcripted and written into the index.html.
But keeping in mind that the format of the Website doesn't get disturbed.

**Comment by samc18** [comment]
Hi @EshanTrivedi21 I would like to help out with this!

**Comment by EshanTrivedi21** [comment]
Heyy!! Thanks for your involvement.. 
I have assigned you this task!
Go on, All the Best :)

**Comment by Tiansing** [comment]
I would like to participate as well

**Comment by EshanTrivedi21** [comment]
Greatt!!! Go on Buddy!

**Comment by EshanTrivedi21** [comment]
hello @samc18,
what you can do is while filing your pr you can add @Tiansing as a coauthor and then he can review your changes and then send his coauthored pr as well.. this is one way of working together it would be a great experience..
great work @samc18!
any progress with your work @Tiansing ??

**Comment by samc18** [comment]
Hi @EshanTrivedi21, perfect, thanks for the tips! I'll be reviewing the whole content of the index.html to make sure is 100% in line with the txt file and I'll be submitting a new PR later today with @Tiansing as coauthor.

Thanks!

**Comment by EshanTrivedi21** [comment]
@samc18 you're doing a great work buddy go on!

**Comment by samc18** [comment]
hi @EshanTrivedi21 I have the PR ready but I can not find an option to add a co-author on the Open a Pull Request page, perhaps am I missing something?

**Comment by EshanTrivedi21** [comment]
Heyy @samc18 dont worry brother.. @Tiansing is not replying you can take the complete charge here!

**Comment by EshanTrivedi21** [comment]
also @samc18 pls refer your pull request here

**Comment by EshanTrivedi21** [comment]
closing this issue. congratulations and great work @samc18!
