### ISSUE TITLE
Adoc Unreadable

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#23]
The Adoc file is complete but the end doesn't look good and is not much readable

**Comment by FinnKr** [comment]
What exactly do you mean by that? Do you want it to be better formatted (list, table or something) or do you want to have the text itself changed? Or maybe both :)

**Comment by EshanTrivedi21** [comment]
The text is okay since it is referring to the main text file I created..
But the problem a few people are facing is the readibility. The file is not nicely formatted and is untidy..
I'll assign you this task.. I have no specific format but it should be usable, full independence to you to format it the way you like.
Thank you so much for your Involvement :)

**Comment by FinnKr** [comment]
All right I'll do my best.

**Comment by EshanTrivedi21** [comment]
Thank You so much!!

**Comment by FinnKr** [comment]
I created a PR. Let me know what you think about it. #30

**Comment by EshanTrivedi21** [comment]
@FinnKr @Kedap plz reply asap so that I can take further action!!!

**Comment by FinnKr** [comment]
> @FinnKr @Kedap plz reply asap so that I can take further action!!!

Go ahead. It‘s your repository. I think an additional Asciidoc file is kind of unnecessary if you got the Markdown.

**Comment by EshanTrivedi21** [comment]
Okay Thanks for the review @FinnKr.. I too feel the same.. closing this issue!
