### ISSUE TITLE
Pdf download button on Website

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#24]
A new PDF needs to be created under the Assets Folder..
And a Download Button must be added to the end of the website which Downloads this pdf

**Comment by syprogrammer** [comment]
is it html file

**Comment by EshanTrivedi21** [comment]
Yup it is an html css shell website... so that the contributors are comfortable with contributing

**Comment by EshanTrivedi21** [comment]
it was @KCmean's idea.. Shall I assign this task to you? I will also assign it to @KCmean, you'll can work together.

**Comment by syprogrammer** [comment]
I created a pdf in assests folder from .txt file  and added a download button at the end of website 
here is design with animation please review it if it is ok : https://bit.ly/3yv1wkW

**Comment by EshanTrivedi21** [comment]
It is good but might need some changes.. But you can add a Pull Request I'll change it the way it suits..
Good Work Buddy!!!! Thanks :)

**Comment by EshanTrivedi21** [comment]
@KCmean Aage ke changes karle plz

**Comment by KCmean** [comment]
wait i am trying to make a better pdf and a better position for download button with better UI. let me handle this task

**Comment by EshanTrivedi21** [comment]
Great go on @KCmean

**Comment by EshanTrivedi21** [comment]
@syprogrammer refer your pull request here plz

**Comment by EshanTrivedi21** [comment]
closing this issue... @KCmean take care of this is the #33 issue!
