### ISSUE TITLE
Light/Dark mode Toggle Button (Website)

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#25]
A button needs to be added on the website that toggles between the light and the dark mod, this would increase the reader's readability and user-experience.. Keep in mind that the format is same as the Website's Theme

**Comment by shrutilenka** [comment]
Hey @EshanTrivedi21, I am interested in working on this issue. Could you please assign this to me?

**Comment by EshanTrivedi21** [comment]
Heyy Sure! @shrutilenka 
I'll assign it to you, Thanks for your interest.

**Comment by EshanTrivedi21** [comment]
any progress @shrutilenka ??

**Comment by EshanTrivedi21** [comment]
@aryan-parmar

**Comment by shrutilenka** [comment]
@EshanTrivedi21 yes I'm working on that. will be submitting it by tomorrow.

**Comment by EshanTrivedi21** [comment]
greatt!!
okay thanks.

**Comment by EshanTrivedi21** [comment]
@shrutilenka please reference your pull request here!!

**Comment by EshanTrivedi21** [comment]
so that i can close this issue

**Comment by EshanTrivedi21** [comment]
#39

**Comment by EshanTrivedi21** [comment]
@shrutilenka i need to close this issue.. also to count in as a contributor you need to reference your pull request here..
please do it asap.. many thanks :)

**Comment by shrutilenka** [comment]
#39 
@EshanTrivedi21 
this is my pull request.

**Comment by EshanTrivedi21** [comment]
@shrutilenka seems like the toggle button isn't working on mobiles
Or maybe only on my phone
Are you facing the same issue?

**Comment by shrutilenka** [comment]
@EshanTrivedi21 let me check once again...

**Comment by shrutilenka** [comment]
![lightmode](https://user-images.githubusercontent.com/96660357/195305289-7b871e9b-35f5-47ed-b267-e75ba69a067b.png)
![darkmode](https://user-images.githubusercontent.com/96660357/195305359-f4b4166a-86d2-4885-bc8b-5c546d9584be.png)


@EshanTrivedi21 sir the toggle button is working in mobile view.
its is not responsive but it is working.

**Comment by EshanTrivedi21** [comment]
@shrutilenka It has topped working on the Pc as well..
here is the latest site:
https://eshantrivedi21.github.io/Git-CheatSheet/
check it out here!
@Aatmaj-Zephyr

**Comment by EshanTrivedi21** [comment]
maybe what you have is your fork of the repository, there have been many additions and subtractions and commits after that one.. check it out once!

**Comment by shrutilenka** [comment]
@EshanTrivedi21 okay sir i am fixing the issue by tonight.

**Comment by shrutilenka** [comment]
> @shrutilenka It has topped working on the Pc as well.. here is the latest site: https://eshantrivedi21.github.io/Git-CheatSheet/ check it out here! @Aatmaj-Zephyr


#50 
Done sir!

**Comment by EshanTrivedi21** [comment]
Great work @shrutilenka !
It might have been deleted in a Pr and would have been unnoticed by me.. Sorry.
not an issue... Thanks :)

**Comment by EshanTrivedi21** [comment]
Closing this issue
