### ISSUE TITLE
Website UI

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#33]
The Website's UI is not good enough..
also the UX is not up to the mark, People have been complaining that finding commands is difficult!
this issue needs to be solved asap.. 
issue credits to @KCmean.. plz take charge! Also anyone who needs to join plz cooperate and work with @KCmean.
His idea was to create a landing page having cards on section basis (e.g. Branches and Commits.. ) which redirect to another page having the cheats for the respective section only.

**Comment by EshanTrivedi21** [comment]
#25 #24 #22 these too coincide within this issue!

**Comment by EshanTrivedi21** [comment]
@KCmean take charge!!!

**Comment by EshanTrivedi21** [comment]
@aryan-parmar @KCmean aajao idhar

**Comment by EshanTrivedi21** [comment]
@aryan-parmar @KCmean any progress?

**Comment by subhans11** [comment]
Can't we use the CSS for designing the website?

**Comment by EshanTrivedi21** [comment]
> Can't we use the CSS for designing the website?

It's Css only, the file is in the Assets folder

**Comment by subhans11** [comment]
Can you please elaborate more on @KCmean 's initial idea for UI.

**Comment by EshanTrivedi21** [comment]
The idea was to actually make a landing page having cards for various topics such that the the card redirects us to the cheatsheet of the respective topic only, for e.g. branching.. this would remove the problem faced by people to find out commands!
but since many people were saying that this would rather decrease the user-experience because all the commands wont be available on a single page, which is the main reason as to why cheatsheets are used...
this is the reason @KCmean's idea is dropped.. currently a better UI on the current idea is only preffered, but do you have any other idea? @subhans11

**Comment by subhans11** [comment]
No idea at this moment.

**Comment by EshanTrivedi21** [comment]
Okay then you can continue working on improving the current UI, I'll assign you this task

**Comment by KCmean** [comment]
My idea was basically to utilize more space and make website less scrolling. Like we can change orientation style and rather then using a search button a sideways navigation menu can work to traverse through elements or diffrent sections ... like for branching and its onflicts we can have a whole section name say 'all about branches' in our side navbar and we can work on it to improve it and make it better and at the same time responsive too .. so please look forward to this type of struture.

**Comment by EshanTrivedi21** [comment]
Take charge @KCmean

**Comment by KCmean** [comment]
![image](https://user-images.githubusercontent.com/96841396/195937662-7425cc0f-7441-4377-8583-171c56971a01.png)



this topics can be listed as a part of our sideways navbar and then we can navigate our uder with help oif this

**Comment by KCmean** [comment]
![image](https://user-images.githubusercontent.com/96841396/195965905-d6003a7e-71c8-4e80-924a-606d3a39bc0d.png)

![image](https://user-images.githubusercontent.com/96841396/195965922-3d6b61d7-487f-483c-a930-e7a3833d3255.png)

before after
still some changes are leftt but working.

**Comment by EshanTrivedi21** [comment]
Great one @KCmean 🚀🚀

**Comment by EshanTrivedi21** [comment]
any progress @KCmean @subhans11 ???

**Comment by subhans11** [comment]
Changed the **font** of commands
![fontchnaged](https://user-images.githubusercontent.com/102163333/196028948-5c77e40c-8575-462e-b068-12b93677f3f2.PNG)

**Comment by EshanTrivedi21** [comment]
Great

**Comment by KCmean** [comment]
i think jet pro and jet pro mians would be good a good font type for the code lines

**Comment by EshanTrivedi21** [comment]
code ke liye toh courier hi sahi hai re
