### ISSUE TITLE
Links opening in same tab

### ISSUE THREAD

**Issue by AvadhootK** [EshanTrivedi21/Git-CheatSheet#36]
Hey @EshanTrivedi21 ,
The links to github repositories and github profiles are opening on the same tab. The user has to press "back" in order to come back to the website.
However, the links should open in new tabs to improve the user experience.
Can I work on this issue?

![Screenshot (677)](https://user-images.githubusercontent.com/72447002/194995072-98799ad1-851b-49d6-a191-323feffdb0e8.png)

**Comment by devjj248** [comment]
Check it out #37 PR, This Pointed Issue Fixed

**Comment by AvadhootK** [comment]
@devjj248 , shouldn't we be first assigned to the issue before fixing it?

**Comment by AvadhootK** [comment]
I was asking for me to get assigned to get this issue fixed.

**Comment by EshanTrivedi21** [comment]
Hey @AvadhootK..
Thanks for pointing out this bug.. I will assign you and @devjj248 both this task..
I will review the pull request which was added by @devjj248..
you can review the commit and work on it if you are not satisfied.
or else shall I let you work on this, since it is your issue?
Thanks :)

**Comment by EshanTrivedi21** [comment]
please reply asap @AvadhootK so that I can take further actions..

**Comment by AvadhootK** [comment]
It will be great if i can work on this since I noticed the bug :)

**Comment by AvadhootK** [comment]
By the way, I have also made a pull request and fixed this issue.

**Comment by devjj248** [comment]
@AvadhootK Yes you found this issue, But i saw this issue, after seeing your pointed issue. Just fixed it. In open souorce projects, you are not restrict for someone approval or assignment. Just create PR if you can fixed the issue. I did same. But @EshanTrivedi21 If You want to accept his PR, You are most welcome. I have multiple options for more PRs, I can do it,

**Comment by AvadhootK** [comment]
Thanks :)

**Comment by EshanTrivedi21** [comment]
Sorry brother @devjj248, I accepted @AvadhootK's PR.. You'll can work on other issues supposedly there are many :)
