### ISSUE TITLE
Github Desktop Features

### ISSUE THREAD

**Issue by amyra98** [EshanTrivedi21/Git-CheatSheet#4]
I can add a step-by-step guide on using Github Desktop to perform basic fork, pull, push, and other operations.

**Comment by amyra98** [comment]
@EshanTrivedi21 Can I work on this issue under Hacktoberfest?

**Comment by EshanTrivedi21** [comment]
Yup you can go on.. Thanks.

**Comment by EshanTrivedi21** [comment]
Fixed
