### ISSUE TITLE
Markdown Format

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#42]
The issue is that the current format of Markdown isn't very well formatted.. I have been getting these complaints from a few people!

I would like if someone would take the initiative of completing the markdown and reformatting it to this format ⬇️ 

<a href="https://ibb.co/FWw09w6"><img src="https://i.ibb.co/3sNMwN1/Screenshot-2022-10-11-184712.png" alt="Screenshot-2022-10-11-184712" border="0" /></a>

Thanks :)

@FinnKr please take charge with anyone who wants to take part!

**Comment by bubblecode76** [comment]
can you pls assign this to me? 
also do you want this format for every topic in the file or just the terminal basics topic?

**Comment by EshanTrivedi21** [comment]
Sure @bubblecode76 !!

**Comment by FinnKr** [comment]
@bubblecode76 I guess it should be for every topic which includes Terminal commands.

**Comment by bubblecode76** [comment]
@FinnKr ok thanks

**Comment by EshanTrivedi21** [comment]
Heyy @FinnKr @bubblecode76 
It's like every separate command in a separate code block so like one can copy the code snippet which github provides with its markdown 
For example... 
Github Branch is a Section 
Every Command in the Section is a separate Code Snippet. 
Hope this helps?

**Comment by bubblecode76** [comment]
@EshanTrivedi21 yes thank you

**Comment by EshanTrivedi21** [comment]
Any progress @bubblecode76 @FinnKr ?

**Comment by bubblecode76** [comment]
yes i did start working on it i will complete it soon

**Comment by EshanTrivedi21** [comment]
Great Great @bubblecode76
