### ISSUE TITLE
Cheetsheet topics are too clogged up

### ISSUE THREAD

**Issue by AvadhootK** [EshanTrivedi21/Git-CheatSheet#46]
The links in the cheetsheet topics are too clogged up and is not looking good. 
Can I fix this in order to improve the website appearance?

![Screenshot (682)](https://user-images.githubusercontent.com/72447002/195160936-07e689ac-94c5-49bf-bfdb-28eb79cb5b1c.png)

**Comment by EshanTrivedi21** [comment]
Go on buddy.. I guess @aryan-parmar is working on this as well

**Comment by AvadhootK** [comment]
Thanks!

**Comment by EshanTrivedi21** [comment]
Closing this issue
