### ISSUE TITLE
PDF is not formatted 

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#58]
The PDF needs to be formatted like the Markdown as the whole cheatsheet must follow a uniform format! Someone plz take over this issue! You'll may create a new pdf and delete the previous one as editing it is weird! Thanks :)

**Comment by ibrahim-ogunbiyi** [comment]
Hi, @EshanTrivedi21 can you assign this task to me? Thanks

**Comment by EshanTrivedi21** [comment]
Sure brother.. Take over! Thanks for the involvement :)
Also don't worry much about the UI we can look after it later!

**Comment by EshanTrivedi21** [comment]
Great Work @ibrahim-ogunbiyi, Closing this issue!
