### ISSUE TITLE
Share Button on Website

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#59]
A share button is needed on the website which allows one to share the pdf or any other asset of this repository to others over various platforms..Thanks :)

**Comment by jsvigneshkanna** [comment]
Hi @EshanTrivedi21 ,

Please asssign me this issue, will fix it

**Comment by jsvigneshkanna** [comment]
Hi @EshanTrivedi21 
I couldnt able to implement share functionality for each cheatsheat, as we can only share whole html file

Can i just add share button and we can fix this functionality in further issues, like moving each cheatsheat to different html

**Comment by EshanTrivedi21** [comment]
> Hi @EshanTrivedi21 
> I couldnt able to implement share functionality for each cheatsheat, as we can only share whole html file
> 
> Can i just add share button and we can fix this functionality in further issues, like moving each cheatsheat to different html

Great progress, what we can do here is you can share the pdf instead of the html as the sharing asset.. if this doesn't work you can just add the buttons and I'll try working on it once!

**Comment by EshanTrivedi21** [comment]
great work @jsvigneshkanna, closing this issue, kudos to you!
