### ISSUE TITLE
Search Button on Website

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#60]
A Search button is needed on the website.. which allows easy and comfortable for the user to find commands than to scroll over all day long! Also this the functionality must be of competition with the local (CTRL + F) tag.. Please someone take over this issue.. Thanks :)

**Comment by Abhay5855** [comment]
hey @EshanTrivedi21  Can you Please assign me this issue?

**Comment by EshanTrivedi21** [comment]
Yes @Abhay5855, you can work on this issue with @riteshsoni123

**Comment by EshanTrivedi21** [comment]
@riteshsoni123 plz take charge!

**Comment by Abhay5855** [comment]
@riteshsoni123  I have also assigned the issue I guess we can work it out together , @EshanTrivedi21  thanks for assigning

**Comment by EshanTrivedi21** [comment]
Any progress @riteshsoni123 @Abhay5855 ?

**Comment by Abhay5855** [comment]
Yes Started working on it Kindly provide some more time

**Comment by EshanTrivedi21** [comment]
what's the progress?? @Abhay5855

**Comment by Abhay5855** [comment]
![image](https://user-images.githubusercontent.com/71277980/195999740-0801f2aa-e86d-4527-8d1b-4853e5c8117f.png)

I have Implemented that need some time to add a search icon and functionality @EshanTrivedi21

**Comment by Abhay5855** [comment]
@EshanTrivedi21  I have added the search bar and the search icon as well it is responsive too, and when user scrolls down and clicks ctrl + f  , it goes to the custom search bar and focus on it , Is there anything to add more or the issue was this much

**Comment by EshanTrivedi21** [comment]
Great work buddy!!! Keep up. 
Go on !!! @Abhay5855

**Comment by MSamiDev** [comment]
Hello @EshanTrivedi21 Can you assign me as well, I have already created search feature for it.

**Comment by EshanTrivedi21** [comment]
@Abhay5855 please look into the matter and review the changes made by @MSamiDev once, since you're already working on this issue.. I have reviewed these changes and they same to be fine.. please review the changes once so that I can accept it and you can further make the changes you want 
Great job guys with this @Abhay5855 @MSamiDev

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Sure I will check once with @MSamiDev  and let you know

**Comment by EshanTrivedi21** [comment]
@Abhay5855 do I merge the pr and then you can make tje necessary changes?

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Sure you can do that as well no problem I have also created a PR for the same 
https://github.com/EshanTrivedi21/Git-CheatSheet/pull/77

**Comment by EshanTrivedi21** [comment]
which on do i accept? @Abhay5855

**Comment by EshanTrivedi21** [comment]
There are alot of conflicts coming in your pull request @Abhay5855 , sorting which would take like an hour, what i can do is merge @MSamiDev's pr and then you can change the things you want? this would minimize everyone's work

**Comment by MSamiDev** [comment]
Hello @Abhay5855 and @EshanTrivedi21,

@Abhay5855  do you have some suggested changes that you can make in my PR(Design, Functionality), Then  @EshanTrivedi21  You can merge the PR and then @Abhay5855  can do the necessary changes.

**Comment by EshanTrivedi21** [comment]
yup i will go on with that @MSamiDev, @Abhay5855 plz make the changes you feel like.. great going guys 🚀🚀

**Comment by Abhay5855** [comment]
@MSamiDev Sure man

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Sure you can go with @MSamiDev PR I will make the necessary changes in there if required.

**Comment by EshanTrivedi21** [comment]
@Abhay5855 I have merged @MSamiDev 's pr, please take a look and add a pr making the necessary changes

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Yes sure I will do that

**Comment by Abhay5855** [comment]
@EshanTrivedi21 i have refactored the search bar and add some styling can you check once please
https://github.com/EshanTrivedi21/Git-CheatSheet/pull/84
