### ISSUE TITLE
PDF changes 

### ISSUE THREAD

**Issue by KCmean** [EshanTrivedi21/Git-CheatSheet#66]
As a cheat sheet it should be short and sweet and very handy.. but as you guys can see our pdf is 17 pages long with lots of things which are simply not required at a begginer level. SO please guys hacve a look at the current cheatheet pdf and tell me which all commands can be ommitted to make a new modified version of it.

**Comment by EshanTrivedi21** [comment]
How long is your pdf turning to be? @KCmean

**Comment by KCmean** [comment]
I am trying to keep it small and simnple llike it will consist of very handy commands which are used in day to day and like which are best for people who are gettin newly aquianted with git and github so thats what the plan is

**Comment by EshanTrivedi21** [comment]
nahi re, fir woh cheatsheet nahi rahegi, usse accha sab daal de but try kar concise ho
