### ISSUE TITLE
We can add Extension that enables various features.

### ISSUE THREAD

**Issue by sumanabhi** [EshanTrivedi21/Git-CheatSheet#67]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
We can have the list of Extensions that are available to use for several features. Based on the different OS, we can have this beneficial for beginners.

**Describe alternatives you've considered**
N/A

**Comment by EshanTrivedi21** [comment]
thats a great idea @sumanabhi, though i didnt get quite an idea of it! but i'll assign you the task, you can go on working over it..

**Comment by sumanabhi** [comment]
@EshanTrivedi21 Sure, I will create one PR with some of the good Plugins.

**Comment by EshanTrivedi21** [comment]
any progress @sumanabhi ??

**Comment by sumanabhi** [comment]
Hopefully, in the next couple of hours, I will create one PR for the same.

**Comment by EshanTrivedi21** [comment]
No worries buddy go on @sumanabhi

**Comment by sumanabhi** [comment]
@EshanTrivedi21 Please check PR #78 

I'm under the weather that's why it got delayed.

Now, I have added the basic one. Hopefully will try to add a better one.

**Comment by EshanTrivedi21** [comment]
Can you please add these to the website as well @sumanabhi

**Comment by sumanabhi** [comment]
@EshanTrivedi21 sure will add in sometime.

**Comment by EshanTrivedi21** [comment]
closing this issue! kudos to you @sumanabhi
