### ISSUE TITLE
CODE REFACTORING

### ISSUE THREAD

**Issue by KCmean** [EshanTrivedi21/Git-CheatSheet#69]
I know this has to be done at the last but guys anyone who is sending a pull request make sure that you refactor your code. properly organuze the things that you add or deleete and mention them in you commits descreption. We will carry out this task after every najor update has been done but just keeping this issue here so that people from now on make sure to  properly organuize those big chunks of codes.

**Comment by EshanTrivedi21** [comment]
arey yeh cheez, contributing.md meh daal @KCmean.. issue meh log confuse hojayenge.. rukja mai daalta hu, yeh issue close karra hu
