### ISSUE TITLE
Updating the content in .gitignore Section

### ISSUE THREAD

**Issue by sumanabhi** [EshanTrivedi21/Git-CheatSheet#71]
**Describe the bug**
Right now the .gitignore is having just a Definition in it. 

**To Reproduce**
N/A

**Expected behavior**
I'm going to provide some resources where anyone can generate a basic or preliminary .gitignore file automatically.

**Comment by EshanTrivedi21** [comment]
I dont think that is really necessary, though i will assign you this task
