### ISSUE TITLE
Small UI/UX feature for Button

### ISSUE THREAD

**Issue by SugamKuber** [EshanTrivedi21/Git-CheatSheet#72]
**Is your feature request related to a problem? Please describe.**
When It comes to the UI/UX of the website it looks buggy 

**Describe the solution you'd like**
I would like to add a proper button, The website looks buggy right now

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/86460476/195978794-49ea7af8-8c36-482a-a0cd-62439eb1da9a.png)

**Comment by EshanTrivedi21** [comment]
Go on buddy, assigning you this task

**Comment by EshanTrivedi21** [comment]
closing this issue!
