### ISSUE TITLE
Desktop UI

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#89]
**Is your feature request related to a problem? Please describe.**
Website's UI is a big turnoff

**Describe the solution you'd like**
There is no specific UI uniformity which makes this website look worse than it should have been..
There must be a specific theme followed and I think NEUMORPHISM is a good theme for the website..
NEUMORPHISM
Dark Mode Primary Color: #26282B
Dark Mode Secondary Color: #FF555D
Light Mode Primary Color: #EAEAEA
Light Mode Secondary Color: #26282B

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/98325124/196365848-db99e9d4-5c37-4be2-a860-a0d1bfc91373.png)

**Comment by super-duper-sp** [comment]
Hey,
I am New to Open Source.
Assign, this issue to me, I want to work on this issue.

**Comment by EshanTrivedi21** [comment]
I already have @KCmean working on this issue, i will assign it to you as well, you can work on it under him @super-duper-sp

**Comment by KCmean** [comment]
I am lookinh into this matter we can have more than 1 assigne also so feel free to assign it to someone who is eager

**Comment by ohyahgit** [comment]
I would like to work on this issue
