### ISSUE TITLE
Put the search bar before the Topics list for easy access

### ISSUE THREAD

**Issue by thisisamish** [EshanTrivedi21/Git-CheatSheet#92]
The search bar is too small and is positioned below the topics list. This makes it kinda useless as a person has to scroll down to get to it. I want to put it before the topics list so it remains on the front of the website and is easily accessible.

![image](https://user-images.githubusercontent.com/71922206/196432883-f03e0217-cc61-45a9-9b2e-69aadedf6c92.png)

**Comment by EshanTrivedi21** [comment]
Go on with the work buddy
