### ISSUE TITLE
Enhancement of the search bar section and adding transitions

### ISSUE THREAD

**Issue by pooranjoyb** [EshanTrivedi21/Git-CheatSheet#97]
`Q1: Is your feature request related to a problem? Please describe.`

- In this current version of the page, the search bar in the light mode looks dull as it is not styled. It also does not resemble the search bar present in dark mode, making it unattractive. 
- The contents of the search item should be placed just below the search bar. However in this current version the "Git-GITHUB Cheatsheet Topics" section is between the search-bar and search results.
- The jump from "Git-GITHUB Cheatsheet Topics" section when clicked on a particular topic is instant.

`Q2: Describe the solution you'd like`

- The search bar in the light mode can be styled accordingly similar to dark mode. 
- The search bar should be shifted just below the "Git-GITHUB Cheatsheet Topics" section so that search results are loaded just after the topic is searched.
- The jump from "Git-GITHUB Cheatsheet Topics" can be made smooth using a pinch of CSS.

`Q3: Describe alternatives you've considered`

Alternative feature that I would like to work on the typing animation of the heading of the webpage. Though, the current version looks quite fine.

`Q4: Additional context`

![pic](https://user-images.githubusercontent.com/90945182/196773018-8dd015e4-b22c-4d0a-8071-fe64289e6215.png)

### I would like to work on this issue under Hacktoberfest-2022. Would be glad if you assign this to me :) @EshanTrivedi21

**Comment by EshanTrivedi21** [comment]
Great work noticing, I will assign you this task, you can go on with solving this issue @pooranjoyb

**Comment by pooranjoyb** [comment]
Thanks @EshanTrivedi21 , Getting into it asap :)

**Comment by EshanTrivedi21** [comment]
resolved!
