### ISSUE TITLE
Solving Minor UI Issues

### ISSUE THREAD

**Issue by EshanTrivedi21** [EshanTrivedi21/Git-CheatSheet#99]
## Making the UI look Uniform like the Majority of the Website!
+ ### Dark/Light Toggle Button looks Ugly and is not like the rest of the Website! AND the button is not very Light Mode Friendly!
![image](https://user-images.githubusercontent.com/98325124/196992107-553f36c9-42a4-42d4-8490-e1553c6dc245.png)
+ ### Navigate to Top Button looks Ugly and is not like the rest of the Website! AND the button is not very Light Mode Friendly!
![image](https://user-images.githubusercontent.com/98325124/196993337-2df5af09-cf92-4759-86bd-b046d071d7b6.png)
+ ### Bottom Bar is not Matching the rest of the Website in the Light Mode.
![image](https://user-images.githubusercontent.com/98325124/196992636-5070fd27-c23a-4de2-b332-8b48c996effe.png)
+ ### Light Mode Color Pallete is not up to the Mark and cause Readability Issues!
![image](https://user-images.githubusercontent.com/98325124/196993036-166b816f-3564-423c-bb39-e7ca3b04c8c6.png)
+ ### Making the Website follow the Neumorphism Theme like this below:
![image](https://user-images.githubusercontent.com/98325124/196995320-40c63f17-4c14-4aa4-bb06-1114450c92b4.png)
Anyone of the these or More than one as well are welcome.. Please take the Initiative! Thanks :)

**Comment by EshanTrivedi21** [comment]
Which issue are you opting for (one or more) ? @g4m3r0

**Comment by EshanTrivedi21** [comment]
Cool go on with it @g4m3r0

**Comment by g4m3r0** [comment]
@EshanTrivedi21 What do you think of that so far?
It uses font awesome icons instead of images and the defined CSS theme for colouring.
![image](https://i.imgur.com/ekmQIO2.gif)
![image](https://i.imgur.com/pM1wk4w.gif)

**Comment by EshanTrivedi21** [comment]
@g4m3r0 
+ The Scroll to top button looks perfect, but can it be wrapped around a circle so that it is more noticeable
+ The Sun's font awesome looks weird, otherwise that is okay as well

**Comment by g4m3r0** [comment]
@EshanTrivedi21 I've created a pull request, can you please take a look at the changes that I've made?

**Comment by g4m3r0** [comment]
I just saw another UI issue in the first code box:
![image](https://user-images.githubusercontent.com/9322695/197297410-50c109eb-bff6-4ede-9d73-1e4212dd46a7.png)

Should it be that the icons turn blue when hovered?
For me, that doesn't really fit with the rest of the site.
![image](https://user-images.githubusercontent.com/9322695/197297499-c6b9a990-fb5a-4627-b02f-b5643d96c028.png)

What do you think about replacing the "copy" images of the boxes with fontawesome icons for more consistency?
I can work on those issues too if you want.

**Comment by EshanTrivedi21** [comment]
@g4m3r0 You can change the blue color issue, but I feel the copy button svg suits the best as it the common thing used wherever this copy button is used.. even github
